/**
 * Crypto education video library — networks, consensus, scaling and the
 * narratives/technologies people are discussing (restaking, real-world assets,
 * DePIN, ZK, intents, AI agents …). Same topic shape as VIDEO_TOPICS in
 * video.js, but every illustration is a `diagram` (boxes, arrows, labelled
 * bands) drawn by scripts/render-edu-video.py instead of a price chart.
 *
 * Rules for this library: explain how a thing works and what the trade-off
 * is — never a price view, never a "buy", never a prediction, and no
 * cashtags (compliance kind 'video' blocks them). Network and project names
 * appear as plain words. Selected with `video.library: "crypto"` in the
 * crypto compliance config; rotation is per queue, so this library cycles
 * independently of the stock chart-education videos.
 *
 * Diagram coordinates: 0–100 on both axes, y up. A node is a rounded box
 * centred on (x, y), default 34 × 14 units; `at` values are fractions of the
 * chart phase, like the chart topics.
 */

const n = (id, x, y, label, { sub = null, color = 'blue', at = 0.1, w = 34, h = 14 } = {}) => ({ id, x, y, label, sub, color, at, w, h });
const e = (from, to, { label = null, color = null, dashed = false, at = 0.3 } = {}) => ({ from, to, label, color, dashed, at });
const g = (x1, y1, x2, y2, label, { color = 'blue', at = 0 } = {}) => ({ x1, y1, x2, y2, label, color, at });

export const CRYPTO_VIDEO_TOPICS = [
  {
    id: 'l2-rollups', series: 'Scaling', title: 'Layer 2 Rollups',
    hook: 'Execute off-chain. Settle on Ethereum.',
    captions: ['Thousands of transactions are batched on the L2.', 'The batch and its data are posted to Layer 1.'],
    means: 'A rollup runs transactions on its own chain and posts compressed data back to Ethereum.',
    use: 'Fees drop because many users share one L1 posting, while L1 still settles disputes.',
    question: 'Which L2 do you use most? 👇',
    art: { type: 'diagram',
      groups: [g(3, 52, 97, 98, 'LAYER 2', { color: 'blue' }), g(3, 3, 97, 46, 'LAYER 1 · ETHEREUM', { color: 'green', at: 0.2 })],
      nodes: [n('users', 25, 74, 'Users', { sub: 'many transactions', at: 0.05 }), n('seq', 75, 74, 'Sequencer', { sub: 'orders + batches', at: 0.15 }),
        n('batch', 75, 22, 'Batch posted', { sub: 'compressed data', color: 'green', at: 0.35 }), n('final', 25, 22, 'Settled', { sub: 'on Ethereum', color: 'green', at: 0.55 })],
      edges: [e('users', 'seq', { at: 0.12 }), e('seq', 'batch', { label: 'one L1 post', at: 0.28 }), e('batch', 'final', { color: 'green', at: 0.5 })] },
  },
  {
    id: 'restaking', series: 'Narratives', title: 'Restaking',
    hook: 'One stake, securing more than one network.',
    captions: ['Staked ETH is pledged again to extra services.', 'More rewards — and more ways to be slashed.'],
    means: 'Restaking reuses already-staked assets to secure additional services such as oracles or bridges.',
    use: 'Extra yield comes from extra duties, and each service adds its own slashing conditions.',
    question: 'Is the extra yield worth the extra risk? 👇',
    art: { type: 'diagram',
      nodes: [n('eth', 22, 82, 'Staked ETH', { sub: 'secures Ethereum', color: 'green', at: 0.05 }), n('rest', 72, 82, 'Restaking layer', { sub: 're-pledges the stake', w: 40, at: 0.15 }),
        n('s1', 17, 42, 'Oracle', { w: 28, at: 0.35 }), n('s2', 50, 42, 'Bridge', { w: 28, at: 0.4 }), n('s3', 83, 42, 'Data layer', { w: 28, at: 0.45 }),
        n('risk', 50, 9, 'More slashing conditions', { color: 'red', w: 64, h: 10, at: 0.65 })],
      edges: [e('eth', 'rest', { at: 0.12 }), e('rest', 's1', { at: 0.3 }), e('rest', 's2', { at: 0.34 }), e('rest', 's3', { at: 0.38 })] },
  },
  {
    id: 'rwa-tokenization', series: 'Narratives', title: 'Real-World Assets (RWA)',
    hook: 'Treasuries, credit and real estate — as tokens.',
    captions: ['An issuer holds the asset off-chain.', 'A token on-chain represents the claim.'],
    means: 'Tokenization puts a claim on an off-chain asset, like a Treasury bill, onto a blockchain.',
    use: 'Settlement becomes 24/7 and programmable, but the token is only as good as its issuer.',
    question: 'Which asset should be tokenized next? 👇',
    art: { type: 'diagram',
      nodes: [n('asset', 22, 80, 'Treasury bill', { sub: 'held off-chain', color: 'amber', at: 0.05 }), n('issuer', 72, 80, 'Issuer + custodian', { sub: 'legal claim', w: 42, at: 0.15 }),
        n('token', 72, 42, 'Token on-chain', { sub: 'represents the claim', color: 'green', w: 42, at: 0.3 }), n('use', 22, 42, '24/7 settlement', { sub: 'programmable', color: 'green', at: 0.45 }),
        n('trust', 50, 9, 'Only as good as the issuer', { color: 'red', w: 70, h: 10, at: 0.65 })],
      edges: [e('asset', 'issuer', { at: 0.12 }), e('issuer', 'token', { label: 'mints', at: 0.25 }), e('token', 'use', { color: 'green', at: 0.4 })] },
  },
  {
    id: 'proof-of-stake', series: 'Consensus', title: 'Proof of Stake',
    hook: 'Security from capital at risk, not energy.',
    captions: ['Validators lock up coins as collateral.', 'Break the rules and part of the stake is slashed.'],
    means: 'Validators stake coins to propose and attest to blocks, earning rewards for honest work.',
    use: 'Misbehavior is punished by slashing, so attacking the chain means risking your own stake.',
    question: 'Would you run a validator or delegate? 👇',
    art: { type: 'diagram',
      nodes: [n('stake', 22, 80, 'Staked coins', { sub: 'collateral', at: 0.05 }), n('val', 72, 80, 'Validators', { sub: 'propose + attest', color: 'green', at: 0.15 }),
        n('block', 72, 42, 'New block', { color: 'green', at: 0.3 }), n('reward', 22, 42, 'Rewards', { sub: 'for honest work', color: 'green', at: 0.45 }),
        n('slash', 50, 9, 'Slashing if dishonest', { color: 'red', w: 56, h: 10, at: 0.65 })],
      edges: [e('stake', 'val', { at: 0.12 }), e('val', 'block', { at: 0.25 }), e('block', 'reward', { color: 'green', at: 0.4 })] },
  },
  {
    id: 'zk-proofs', series: 'Technology', title: 'Zero-Knowledge Proofs',
    hook: 'Prove it is true without showing the data.',
    captions: ['The prover creates a small cryptographic proof.', 'Anyone can verify it quickly — the data stays private.'],
    means: 'A zero-knowledge proof shows a statement is true without revealing the underlying data.',
    use: 'Blockchains use them to scale (ZK rollups) and to add privacy to payments and identity.',
    question: 'Privacy or scaling — the bigger use case? 👇',
    art: { type: 'diagram',
      nodes: [n('prover', 22, 80, 'Prover', { sub: 'has the secret data', at: 0.05 }), n('proof', 72, 80, 'Small proof', { sub: 'no data inside', color: 'amber', at: 0.18 }),
        n('verifier', 72, 42, 'Verifier', { sub: 'checks it quickly', color: 'green', at: 0.32 }), n('ok', 22, 42, 'Verified true', { sub: 'data stays private', color: 'green', at: 0.46 }),
        n('uses', 50, 9, 'Used for scaling + privacy', { w: 66, h: 10, at: 0.65 })],
      edges: [e('prover', 'proof', { at: 0.14 }), e('proof', 'verifier', { at: 0.28 }), e('verifier', 'ok', { color: 'green', at: 0.42 })] },
  },
  {
    id: 'stablecoins', series: 'Stablecoins', title: 'How Stablecoins Hold $1',
    hook: 'A crypto dollar is only as good as its backing.',
    captions: ['Fiat-backed: cash and T-bills held by an issuer.', 'Crypto-backed: over-collateralized on-chain loans.'],
    means: 'Tokens designed to track $1, backed by reserves, crypto collateral or an algorithm.',
    use: 'They are the settlement currency of on-chain markets; the risks are the peg and the issuer.',
    question: 'Which backing model do you trust most? 👇',
    art: { type: 'diagram',
      nodes: [n('fiat', 17, 80, 'Fiat reserves', { sub: 'cash + T-bills', color: 'green', w: 30, at: 0.05 }), n('crypto', 50, 80, 'Crypto', { sub: 'over-collateral', w: 30, at: 0.12 }),
        n('algo', 83, 80, 'Algorithm', { sub: 'supply rules', color: 'amber', w: 30, at: 0.19 }), n('stable', 50, 44, 'Stablecoin', { sub: 'tracks $1', color: 'green', w: 40, at: 0.35 }),
        n('markets', 50, 10, 'On-chain markets', { sub: 'trading · payments', w: 50, h: 13, at: 0.55 })],
      edges: [e('fiat', 'stable', { at: 0.3 }), e('crypto', 'stable', { at: 0.32 }), e('algo', 'stable', { color: 'amber', dashed: true, at: 0.34 }), e('stable', 'markets', { at: 0.5 })] },
  },
  {
    id: 'depin', series: 'Narratives', title: 'DePIN',
    hook: 'Crowdsourcing real-world infrastructure.',
    captions: ['People run hardware: hotspots, storage, sensors.', 'The network pays them in tokens for proven work.'],
    means: 'Decentralized physical infrastructure networks reward people for supplying real hardware.',
    use: 'Tokens bootstrap coverage fast; lasting value depends on paying customers using it.',
    question: 'Would you run a node at home? 👇',
    art: { type: 'diagram',
      nodes: [n('hw', 22, 80, 'Hardware', { sub: 'hotspots · storage', at: 0.05 }), n('net', 72, 80, 'Network', { sub: 'verifies the work', at: 0.15 }),
        n('tok', 72, 42, 'Token rewards', { sub: 'for proven supply', color: 'amber', at: 0.3 }), n('cust', 22, 42, 'Customers', { sub: 'pay for the service', color: 'green', at: 0.45 }),
        n('value', 50, 9, 'Real demand = lasting value', { color: 'green', w: 70, h: 10, at: 0.65 })],
      edges: [e('hw', 'net', { label: 'supplies', at: 0.12 }), e('net', 'tok', { at: 0.26 }), e('cust', 'net', { color: 'green', label: 'pays', at: 0.42 })] },
  },
  {
    id: 'lightning-network', series: 'Networks', title: 'Bitcoin Lightning Network',
    hook: 'Instant bitcoin payments off the main chain.',
    captions: ['Opening a channel takes one on-chain transaction.', 'Payments route instantly; the final balance settles on-chain.'],
    means: 'Lightning is a network of payment channels that move bitcoin off-chain and settle later.',
    use: 'It makes small, fast payments practical; channels need liquidity and must stay online.',
    question: 'Have you sent a Lightning payment? 👇',
    art: { type: 'diagram',
      nodes: [n('open', 50, 86, 'Open channel', { sub: 'one on-chain tx', w: 46, h: 12, at: 0.05 }),
        n('alice', 16, 52, 'Alice', { w: 26, at: 0.18 }), n('hub', 50, 52, 'Routing node', { w: 32, color: 'amber', at: 0.22 }), n('bob', 84, 52, 'Bob', { w: 26, at: 0.26 }),
        n('close', 50, 14, 'Close channel', { sub: 'final balance on-chain', color: 'green', w: 50, h: 14, at: 0.6 })],
      edges: [e('open', 'hub', { at: 0.15 }), e('alice', 'hub', { label: 'instant', color: 'green', at: 0.35 }), e('hub', 'bob', { label: 'instant', color: 'green', at: 0.42 }), e('hub', 'close', { at: 0.55 })] },
  },
  {
    id: 'ai-agents', series: 'Narratives', title: 'AI Agents On-Chain',
    hook: 'Software that holds a wallet and acts on its own.',
    captions: ['An AI agent gets a wallet and a set of permissions.', 'It can pay, trade or call contracts without a human click.'],
    means: 'AI agents are programs that control crypto wallets and transact on-chain by themselves.',
    use: 'Blockchains give software native payments, so key security and spending limits become critical.',
    question: 'Would you let an agent spend from your wallet? 👇',
    art: { type: 'diagram',
      nodes: [n('owner', 22, 82, 'You', { sub: 'set the permissions', at: 0.05 }), n('agent', 72, 82, 'AI agent', { sub: 'holds a wallet', color: 'amber', at: 0.15 }),
        n('a1', 17, 42, 'Pay', { w: 26, color: 'green', at: 0.35 }), n('a2', 50, 42, 'Trade', { w: 26, color: 'green', at: 0.4 }), n('a3', 83, 42, 'Call contracts', { w: 30, color: 'green', at: 0.45 }),
        n('lim', 50, 9, 'Spending limits matter', { color: 'red', w: 58, h: 10, at: 0.65 })],
      edges: [e('owner', 'agent', { label: 'limits', at: 0.12 }), e('agent', 'a1', { at: 0.3 }), e('agent', 'a2', { at: 0.34 }), e('agent', 'a3', { at: 0.38 })] },
  },
  {
    id: 'oracles', series: 'Infrastructure', title: 'Oracles',
    hook: 'Blockchains cannot see the outside world.',
    captions: ['Oracle nodes fetch prices from many sources.', 'An aggregated value is posted on-chain for apps.'],
    means: 'Oracles bring off-chain data, such as asset prices, onto a blockchain for smart contracts.',
    use: 'Lending and derivatives depend on them — a stale price feed can trigger wrong liquidations.',
    question: 'What data should oracles bring on-chain next? 👇',
    art: { type: 'diagram',
      nodes: [n('s1', 17, 82, 'Exchange A', { w: 28, at: 0.05 }), n('s2', 50, 82, 'Exchange B', { w: 28, at: 0.1 }), n('s3', 83, 82, 'Exchange C', { w: 28, at: 0.15 }),
        n('orc', 50, 48, 'Oracle network', { sub: 'aggregates the prices', color: 'amber', w: 50, at: 0.3 }),
        n('app', 50, 14, 'Smart contract', { sub: 'reads the price', color: 'green', w: 50, at: 0.5 })],
      edges: [e('s1', 'orc', { at: 0.22 }), e('s2', 'orc', { at: 0.25 }), e('s3', 'orc', { at: 0.28 }), e('orc', 'app', { color: 'green', at: 0.45 })] },
  },
  {
    id: 'liquid-staking', series: 'Staking', title: 'Liquid Staking',
    hook: 'Stake your coins and keep them usable.',
    captions: ['Deposit into a staking protocol, receive a receipt token.', 'The receipt token can move through DeFi.'],
    means: 'A protocol stakes your coins and gives you a token that represents the staked position.',
    use: 'It frees capital that would otherwise sit locked, and adds smart-contract and depeg risk.',
    question: 'Do you stake natively or through a protocol? 👇',
    art: { type: 'diagram',
      nodes: [n('you', 22, 82, 'Your coins', { at: 0.05 }), n('proto', 72, 82, 'Staking protocol', { sub: 'stakes for you', w: 40, at: 0.15 }),
        n('val', 72, 44, 'Validators', { sub: 'earn rewards', color: 'green', at: 0.3 }), n('lst', 22, 44, 'Receipt token', { sub: 'the staked position', color: 'amber', at: 0.4 }),
        n('defi', 22, 10, 'DeFi', { sub: 'lend · trade · pool', w: 34, h: 13, at: 0.6 })],
      edges: [e('you', 'proto', { at: 0.12 }), e('proto', 'val', { at: 0.26 }), e('proto', 'lst', { label: 'mints', color: 'amber', at: 0.36 }), e('lst', 'defi', { at: 0.55 })] },
  },
  {
    id: 'intents', series: 'Narratives', title: 'Intents & Chain Abstraction',
    hook: 'Say what you want, not how to do it.',
    captions: ['You sign an intent: swap A for B at this price or better.', 'Solvers compete to fill it, on whichever chain works.'],
    means: 'An intent is a signed goal; solvers find the route, chain and liquidity to fulfil it.',
    use: 'It hides chain complexity from users, who then rely on solvers and the settlement rules.',
    question: 'Should wallets hide which chain you are on? 👇',
    art: { type: 'diagram',
      nodes: [n('user', 22, 82, 'You', { sub: 'sign an intent', at: 0.05 }), n('intent', 72, 82, 'Intent', { sub: 'swap A for B', color: 'amber', at: 0.15 }),
        n('s1', 17, 44, 'Solver 1', { w: 26, at: 0.3 }), n('s2', 50, 44, 'Solver 2', { w: 26, at: 0.34 }), n('s3', 83, 44, 'Solver 3', { w: 26, at: 0.38 }),
        n('best', 50, 10, 'Best fill wins', { sub: 'on any chain', color: 'green', w: 44, h: 13, at: 0.62 })],
      edges: [e('user', 'intent', { at: 0.12 }), e('intent', 's1', { at: 0.26 }), e('intent', 's2', { at: 0.3 }), e('intent', 's3', { at: 0.34 }), e('s2', 'best', { color: 'green', at: 0.56 })] },
  },
  {
    id: 'bridges', series: 'Security', title: 'Cross-Chain Bridges',
    hook: 'Moving coins between chains is a trust decision.',
    captions: ['Lock on chain A, mint a wrapped copy on chain B.', 'The locked pool is what attackers go after.'],
    means: 'A bridge locks assets on one chain and issues a representation of them on another.',
    use: 'Bridges hold large pooled funds, so their security model matters more than their speed.',
    question: 'Do you check a bridge before using it? 👇',
    art: { type: 'diagram',
      groups: [g(3, 8, 44, 96, 'CHAIN A'), g(56, 8, 97, 96, 'CHAIN B', { color: 'green', at: 0.1 })],
      nodes: [n('lock', 23.5, 70, 'Lock', { sub: 'coins in a vault', color: 'amber', w: 34, at: 0.1 }), n('mint', 76.5, 70, 'Mint', { sub: 'wrapped copy', color: 'green', w: 34, at: 0.3 }),
        n('burn', 76.5, 30, 'Burn', { sub: 'to go back', w: 34, at: 0.5 }), n('release', 23.5, 30, 'Release', { sub: 'from the vault', w: 34, at: 0.62 })],
      edges: [e('lock', 'mint', { label: 'message', at: 0.22 }), e('burn', 'release', { label: 'message', at: 0.58 })] },
  },
  {
    id: 'account-abstraction', series: 'Wallets', title: 'Smart Wallets',
    hook: 'A wallet that is a program, not just a key.',
    captions: ['The rules live in a smart contract, not one seed phrase.', 'Recovery, spending limits and batched actions become possible.'],
    means: 'Account abstraction lets a wallet be a smart contract with its own security rules.',
    use: 'It enables social recovery, gas paid by apps and one-click batched transactions.',
    question: 'Would you trade your seed phrase for social recovery? 👇',
    art: { type: 'diagram',
      nodes: [n('key', 22, 82, 'Seed phrase', { sub: 'single point of failure', color: 'red', w: 38, at: 0.05 }), n('sw', 74, 82, 'Smart wallet', { sub: 'a contract', color: 'green', at: 0.2 }),
        n('r1', 17, 42, 'Social recovery', { w: 30, at: 0.36 }), n('r2', 50, 42, 'Spending limits', { w: 30, at: 0.4 }), n('r3', 83, 42, 'Batched actions', { w: 30, at: 0.44 }),
        n('gas', 50, 9, 'Apps can pay the gas', { w: 56, h: 10, at: 0.65 })],
      edges: [e('key', 'sw', { label: 'upgrade', at: 0.15 }), e('sw', 'r1', { at: 0.32 }), e('sw', 'r2', { at: 0.36 }), e('sw', 'r3', { at: 0.4 })] },
  },
  {
    id: 'modular-vs-monolithic', series: 'Architecture', title: 'Modular vs Monolithic',
    hook: 'One chain for everything — or specialist layers?',
    captions: ['Monolithic: one chain executes, orders and stores data.', 'Modular: separate layers for execution, settlement and data.'],
    means: 'Monolithic chains do every job on one layer; modular designs split the jobs across layers.',
    use: 'Monolithic keeps it simple and fast; modular trades complexity for flexibility and scale.',
    question: 'Team monolithic or team modular? 👇',
    art: { type: 'diagram',
      groups: [g(3, 4, 40, 96, 'MONOLITHIC', { color: 'amber' }), g(46, 4, 97, 96, 'MODULAR', { color: 'green', at: 0.25 })],
      nodes: [n('mono', 21.5, 48, 'One chain', { sub: 'execute · order · store', color: 'amber', w: 32, h: 40, at: 0.08 }),
        n('ex', 71.5, 76, 'Execution', { sub: 'rollups', w: 44, h: 13, at: 0.32 }), n('set', 71.5, 48, 'Settlement', { w: 44, h: 13, at: 0.42 }), n('da', 71.5, 20, 'Data availability', { w: 44, h: 13, at: 0.52 })],
      edges: [e('ex', 'set', { at: 0.4 }), e('set', 'da', { at: 0.5 })] },
  },
  {
    id: 'proof-of-work', series: 'Consensus', title: 'Proof of Work (Bitcoin)',
    hook: 'Bitcoin is secured by computing power.',
    captions: ['Miners race to find a valid block hash.', 'Difficulty adjusts every 2,016 blocks, about two weeks.'],
    means: 'Miners spend computing power to add blocks; the winner earns new bitcoin plus fees.',
    use: 'Rewriting history means redoing that work, which is why deep confirmations are trusted.',
    question: 'How many confirmations do you wait for? 👇',
    art: { type: 'diagram',
      nodes: [n('tx', 22, 82, 'Transactions', { at: 0.05 }), n('pool', 72, 82, 'Mempool', { sub: 'waiting room', at: 0.12 }),
        n('miners', 72, 46, 'Miners', { sub: 'hash race', color: 'amber', at: 0.25 }), n('block', 22, 46, 'New block', { sub: 'about 10 minutes', color: 'green', at: 0.4 }),
        n('chain', 50, 11, 'Most-work chain', { sub: 'the valid history', color: 'green', w: 50, h: 13, at: 0.6 })],
      edges: [e('tx', 'pool', { at: 0.1 }), e('pool', 'miners', { at: 0.22 }), e('miners', 'block', { label: 'winner', color: 'green', at: 0.36 }), e('block', 'chain', { at: 0.55 })] },
  },
  {
    id: 'bitcoin-halving', series: 'Networks', title: 'The Bitcoin Halving',
    hook: 'New bitcoin issuance is cut in half on a schedule.',
    captions: ['Every 210,000 blocks, the block reward halves.', 'Supply is capped at 21 million coins.'],
    means: 'The halving cuts the new-coin reward paid to miners roughly every four years.',
    use: 'It makes issuance predictable, and miners lean more on transaction fees over time.',
    question: 'How do fees matter as the reward shrinks? 👇',
    art: { type: 'diagram',
      nodes: [n('h1', 15, 84, '2012', { sub: '25 BTC / block', w: 26, h: 13, at: 0.05 }), n('h2', 38, 64, '2016', { sub: '12.5 BTC', w: 26, h: 13, at: 0.18 }),
        n('h3', 61, 44, '2020', { sub: '6.25 BTC', w: 26, h: 13, at: 0.31 }), n('h4', 84, 24, '2024', { sub: '3.125 BTC', color: 'amber', w: 26, h: 13, at: 0.44 }),
        n('cap', 30, 12, '21 million cap', { color: 'green', w: 44, h: 10, at: 0.62 })],
      edges: [e('h1', 'h2', { at: 0.14 }), e('h2', 'h3', { at: 0.27 }), e('h3', 'h4', { at: 0.4 })] },
  },
  {
    id: 'optimistic-vs-zk', series: 'Scaling', title: 'Optimistic vs ZK Rollups',
    hook: 'Two ways to prove a batch is valid.',
    captions: ['Optimistic: assume valid, allow a challenge window.', 'ZK: attach a validity proof to every batch.'],
    means: 'Optimistic rollups rely on fraud proofs; ZK rollups post cryptographic validity proofs.',
    use: 'The difference shows in withdrawals: about a week for optimistic, faster once a ZK proof is verified.',
    question: 'Speed or simplicity — which matters more? 👇',
    art: { type: 'diagram',
      groups: [g(3, 3, 48, 97, 'OPTIMISTIC', { color: 'amber' }), g(52, 3, 97, 97, 'ZK', { color: 'green', at: 0.2 })],
      nodes: [n('o1', 25.5, 76, 'Batch', { sub: 'assumed valid', color: 'amber', w: 38, at: 0.08 }), n('o2', 25.5, 46, 'Challenge window', { sub: 'about 7 days', color: 'amber', w: 40, at: 0.2 }),
        n('o3', 25.5, 16, 'Final', { color: 'green', w: 38, at: 0.34 }), n('z1', 74.5, 76, 'Batch', { sub: '+ validity proof', color: 'green', w: 38, at: 0.26 }),
        n('z2', 74.5, 46, 'Proof verified', { sub: 'on Layer 1', color: 'green', w: 40, at: 0.38 }), n('z3', 74.5, 16, 'Final', { color: 'green', w: 38, at: 0.5 })],
      edges: [e('o1', 'o2', { at: 0.16 }), e('o2', 'o3', { at: 0.3 }), e('z1', 'z2', { at: 0.34 }), e('z2', 'z3', { at: 0.46 })] },
  },
];
